### ISSUE TITLE
Convert LatLong from GEO to ACGM for year 2021

### ISSUE THREAD

**Issue by zemarchezi** [aburrell/aacgmv2#69]
I'm trying to convert the coordinates, from geographic to geomagnetic, for 2021-04-12, and I got an error, saying that it is impossible to set that time in the "AACGM_v2_SetDateTime" function. 

I'm using Python 3.9.

import datetime
import aacgmv2
dt = datetime.datetime.strptime('20210412', '%Y%m%d')

cgm_lat, cgm_lon, cgm_r = aacgmv2.convert_latlon(53.856, 265.34, 100., dt, method_code='G2A')

--

See below the error print:

-----
File ".local/lib/python3.9/site-packages/aacgmv2/wrapper.py", line 229, in convert_latlon
    raise RuntimeError("cannot set time for {:}: {:}".format(dtime, err))
RuntimeError: cannot set time for 2021-04-12 00:00:00: AACGM_v2_SetDateTime returned error code -2
----

- OS:Manjaro 
- Version 21.0.1
- Python 3.9

**Comment by aburrell** [comment]
Following your exact code snippit on:
- python 3.9.2 
- AACGMV2 2.6.2 
- mac OS X Mojave
 
I get no error.
```
import aacgmv2
import datetime
dt = datetime.datetime.strptime('20210412', '%Y%m%d')
cgm_lat, cgm_lon, cgm_r = aacgmv2.convert_latlon(53.856, 265.34, 100., dt, method_code='G2A')
print(cgm_lat, cgm_lon, cgm_r)
```

Yields
```
62.83778754706739 -24.704534620533988 1.014601955600466
```

What version of AACGMV2 are you using?  Since Manjaro is Linux, I expect it to behave sensibly.  However, the date you're using would cause issues with older versions of AACGMV2 since the coefficients don't go that far into their future.

**Comment by zemarchezi** [comment]
Thank you!

I believe the problem was in some update in my system. I tried another computer today, and it works fine.  

Thank you again.
